.DATA 0002H
DB 09H ; X
DB 02H    ; n
DB 0BH    
DB 10H    
DB 0Eh     ;datos para A
.ORG 100H
MVI B,00H ; Puntero B y C dan la posición 0002H
MVI C,02H
LDAX B
MOV D, A ; D RECIBE X
INX B ; SE inCREMENTA BC
LDAX B ; SE VA A A N
MOV E, A ; E RECIBE LA POTENCIA
MOV A, D ; A RECIBE X
MOV H, D ; H RECIBE X
MOV L, D ; L RECIBE X
DCR E ; SE DECREMENTA LA POTENCIA i
EXP: 
DCR D
JZ EXP2
ADD H ; SE VA SUMANDO X HASTA QUE SE CUMPLA X VECES POR EJEMPLO 5*5 ES SUMAR 5 VECES 5
JMP EXP ; SE REPITE CICLO DEL EXPONENTE
EXP2:
MOV D, L ;SE VUELVE A CARGAR D PARA VOLVER A HACER LA SUMATORIA
MOV H,A ; SE CARGA H CON EL DATO QUE LLEVA A PARA HACER AHORA LA SUMATORIA CON ESE NUMERO
DCR E ; SE DECREMENTA LA POTENCIA
JZ MULT; SE CHECA SI NO HA LLEGADO LA POTENCIA A 0
JMP EXP ;SE REPITE LA SUMATORIA DEL EXPONENTE
MOV D, H
MULT: ; SE HACE LA MULTIPLICACION CON A
mvi d, 00h ; SE INICIALIZA EN 0 PORQUE AQUI SE GUARDARA EL RESULTADO DE LA MULTIPLICACION
inr c ; SE INCREMENTA C PARA OBTENER EL DATO A MULTIPLICAR
mov l, a ; L RECIBE EL RESULTADO DE LA SUMATORIA DE X
DCR L, ;E DECREMENTA L 
ldax b ; SE OBTIENE EL DATO A MULTIPLICAR (A)
mov h, a ; SE ENCIA A H
MOV E ,A ; SE PONE EN E PORQUE AUI SE VA IR GUARDANDO EL RESULTADO
MULT2:
mov e, a
MOV A, E
add H  ; SE VA HACIENDO LA SUMA
JC CARRY ; SE CONFIRMA SI HAY CARRY
dcr l ; SE DECREMENTA PARA LLEGAR A 0
jz MANDARDATO ; SE CONFIRMA SI LLEGA A 0
JMP MULT2 ; SE REPITE EL CICLO
CARRY: 
INR D ; SE INCREMENTA D PORQUE ES EL MAS SIGNIFICATIVO
MOV E, A 
dcr l   ;SE DECREMENTA EL MULTIPLCADOR PARA QUE NO SE SUME 2 VECES
jz MANDARDATO ; SE CONFIRMA SI NO HA LLEGADO A 0
JMP MULT2 ; SE REPITE EL CICLO
MANDARDATO:
MOV E,A ; SE GUARDA EL DATO FINAL LOW
PUSH D ; SE MANDA A MEMORIA PILA
INR C

hlt

